# Generated by Django 3.0.7 on 2020-06-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200617_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_int',
            field=models.IntegerField(choices=[(0, 'black'), (1, 'white'), (2, 'red')], default=0),
        ),
    ]
