# Generated by Django 3.0.7 on 2020-06-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200617_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Максимальная длина 254 символа', max_length=255, unique_for_date='date', verbose_name='Название'),
        ),
    ]
