# Generated by Django 3.0.7 on 2020-06-17 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200617_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus_positive',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(error_messages={'unique_for_date': 'some error'}, help_text='Максимальная длина 254 символа', max_length=255, unique_for_date='date', verbose_name='Название'),
        ),
    ]
