# Generated by Django 3.0.7 on 2020-06-17 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200617_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
