# Generated by Django 3.0.7 on 2020-06-20 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='bonus_positive',
        ),
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(error_messages={'unique_for_date': 'some error'}, help_text='Максимальная длина 255 символов', max_length=255, unique_for_date='date', verbose_name='Название'),
        ),
    ]
